  
version: "3.8"

services:
  cms_frontend:
    container_name: cms_frontend
    build: ./cms_frontend
    volumes:
      # Note must include node_modules as a seperate volume
      - '/app/node_modules'
      - './cms_frontend:/app'
    stdin_open: true
    ports:
      - 3000:3000
  backend:
    container_name: go_backend
    build: ./Backend
    volumes:
      - './Backend:/app'
    ports:
      - 8080:8080
